<?php

namespace ContainerESJmAZx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0y7zlJqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0y7zlJq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0y7zlJq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'EventsRepository' => ['privates', 'App\\Repository\\EventsRepository', 'getEventsRepositoryService', true],
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'usersRepository' => ['privates', '.errored..service_locator.0y7zlJq.App\\Repository\\UsersRepository', NULL, 'Cannot autowire service ".service_locator.0y7zlJq": it references class "App\\Repository\\UsersRepository" but no such service exists.'],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'EventsRepository' => 'App\\Repository\\EventsRepository',
            'cache' => '?',
            'entityManager' => '?',
            'serializer' => '?',
            'usersRepository' => 'App\\Repository\\UsersRepository',
            'validator' => '?',
        ]);
    }
}
