<?php

namespace ContainerESJmAZx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersRepository2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MbAeCxw.App\Repository\UsersRepository' shared service.
     *
     * @return \App\Repository\UsersRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MbAeCxw": it references class "App\\Repository\\UsersRepository" but no such service exists.');
    }
}
