<?php

namespace ContainerRf7WuOw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0EWeJwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0E_WeJw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0E_WeJw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'EventsRepository' => ['privates', 'App\\Repository\\EventsRepository', 'getEventsRepositoryService', true],
            'UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\EventsRepository', 'getEventsRepositoryService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'EventsRepository' => 'App\\Repository\\EventsRepository',
            'UserRepository' => 'App\\Repository\\UserRepository',
            'cache' => '?',
            'entityManager' => '?',
            'repository' => 'App\\Repository\\EventsRepository',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
