<?php

namespace ContainerRf7WuOw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QbN1lfgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QbN1lfg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QbN1lfg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\EventsController::createEvents' => ['privates', '.service_locator.eBptWAA', 'get_ServiceLocator_EBptWAAService', true],
            'App\\Controller\\EventsController::deleteEvents' => ['privates', '.service_locator.Q43bnhM', 'get_ServiceLocator_Q43bnhMService', true],
            'App\\Controller\\EventsController::getAllEvents' => ['privates', '.service_locator.NCb_sxm', 'get_ServiceLocator_NCbSxmService', true],
            'App\\Controller\\EventsController::getEvents' => ['privates', '.service_locator.cbokvuV', 'get_ServiceLocator_CbokvuVService', true],
            'App\\Controller\\EventsController::updateEvents' => ['privates', '.service_locator.0E_WeJw', 'get_ServiceLocator_0EWeJwService', true],
            'App\\Controller\\UserController::deleteUser' => ['privates', '.service_locator.Pxg2oMN', 'get_ServiceLocator_Pxg2oMNService', true],
            'App\\Controller\\UserController::getCurrentUserInfos' => ['privates', '.service_locator.7lseJss', 'get_ServiceLocator_7lseJssService', true],
            'App\\Controller\\UserController::getUserById' => ['privates', '.service_locator.IH3CvJn', 'get_ServiceLocator_IH3CvJnService', true],
            'App\\Controller\\UserController::registerUser' => ['privates', '.service_locator.dCdKidd', 'get_ServiceLocator_DCdKiddService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\EventsController:createEvents' => ['privates', '.service_locator.eBptWAA', 'get_ServiceLocator_EBptWAAService', true],
            'App\\Controller\\EventsController:deleteEvents' => ['privates', '.service_locator.Q43bnhM', 'get_ServiceLocator_Q43bnhMService', true],
            'App\\Controller\\EventsController:getAllEvents' => ['privates', '.service_locator.NCb_sxm', 'get_ServiceLocator_NCbSxmService', true],
            'App\\Controller\\EventsController:getEvents' => ['privates', '.service_locator.cbokvuV', 'get_ServiceLocator_CbokvuVService', true],
            'App\\Controller\\EventsController:updateEvents' => ['privates', '.service_locator.0E_WeJw', 'get_ServiceLocator_0EWeJwService', true],
            'App\\Controller\\UserController:deleteUser' => ['privates', '.service_locator.Pxg2oMN', 'get_ServiceLocator_Pxg2oMNService', true],
            'App\\Controller\\UserController:getCurrentUserInfos' => ['privates', '.service_locator.7lseJss', 'get_ServiceLocator_7lseJssService', true],
            'App\\Controller\\UserController:getUserById' => ['privates', '.service_locator.IH3CvJn', 'get_ServiceLocator_IH3CvJnService', true],
            'App\\Controller\\UserController:registerUser' => ['privates', '.service_locator.dCdKidd', 'get_ServiceLocator_DCdKiddService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\EventsController::createEvents' => '?',
            'App\\Controller\\EventsController::deleteEvents' => '?',
            'App\\Controller\\EventsController::getAllEvents' => '?',
            'App\\Controller\\EventsController::getEvents' => '?',
            'App\\Controller\\EventsController::updateEvents' => '?',
            'App\\Controller\\UserController::deleteUser' => '?',
            'App\\Controller\\UserController::getCurrentUserInfos' => '?',
            'App\\Controller\\UserController::getUserById' => '?',
            'App\\Controller\\UserController::registerUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EventsController:createEvents' => '?',
            'App\\Controller\\EventsController:deleteEvents' => '?',
            'App\\Controller\\EventsController:getAllEvents' => '?',
            'App\\Controller\\EventsController:getEvents' => '?',
            'App\\Controller\\EventsController:updateEvents' => '?',
            'App\\Controller\\UserController:deleteUser' => '?',
            'App\\Controller\\UserController:getCurrentUserInfos' => '?',
            'App\\Controller\\UserController:getUserById' => '?',
            'App\\Controller\\UserController:registerUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
