<?php

namespace ContainerRf7WuOw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CbokvuVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cbokvuV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cbokvuV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cache' => ['services', 'cache.app', 'getCache_AppService', true],
            'repository' => ['privates', 'App\\Repository\\EventsRepository', 'getEventsRepositoryService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'cache' => '?',
            'repository' => 'App\\Repository\\EventsRepository',
            'serializer' => '?',
        ]);
    }
}
